### ISSUE TITLE
我跳转后，页面除了头部为蓝色，文字为空，图标也没有

### ISSUE THREAD

**Issue by zhuewizz** [80percent/react-native-template-mobx#12]

**Comment by windy** [comment]
能截个图么? 还有你用的 react-native 版本

**Comment by windy** [comment]
@zhuewizz 感谢反馈, 问题已经解决, 是 react-navigation 嵌套路由在 android 下表现的bug, 目前切换到 stackNavigator 嵌套 TabNavigator 恢复正常. 之前是相反的方式.
